INSERT INTO exercises (type, statement, solution) VALUES (102, '10-10', '0');
INSERT INTO exercises (type, statement, solution) VALUES (102, '6 \\times 7', '42');
INSERT INTO exercises (type, statement, solution) VALUES (102, '5+0', '5');
INSERT INTO exercises (type, statement, solution) VALUES (102, '14-7', '7');
INSERT INTO exercises (type, statement, solution) VALUES (102, '12:4', '3');
INSERT INTO exercises (type, statement, solution) VALUES (102, '6+7', '13');
INSERT INTO exercises (type, statement, solution) VALUES (102, '14:7', '2');
INSERT INTO exercises (type, statement, solution) VALUES (102, '9 \\times 3', '27');
INSERT INTO exercises (type, statement, solution) VALUES (102, '10:5', '2');
INSERT INTO exercises (type, statement, solution) VALUES (102, '2+7', '9');
INSERT INTO exercises (type, statement, solution) VALUES (102, '10+9', '19');
INSERT INTO exercises (type, statement, solution) VALUES (102, '10+5', '15');
INSERT INTO exercises (type, statement, solution) VALUES (102, '9-9', '0');
INSERT INTO exercises (type, statement, solution) VALUES (102, '0+1', '1');
INSERT INTO exercises (type, statement, solution) VALUES (102, '0:6', '0');
INSERT INTO exercises (type, statement, solution) VALUES (102, '3 \\times 2', '6');
INSERT INTO exercises (type, statement, solution) VALUES (102, '32:4', '8');
INSERT INTO exercises (type, statement, solution) VALUES (102, '12:3', '4');
INSERT INTO exercises (type, statement, solution) VALUES (102, '60:6', '10');
INSERT INTO exercises (type, statement, solution) VALUES (102, '9+0', '9');
INSERT INTO exercises (type, statement, solution) VALUES (102, '14-9', '5');
INSERT INTO exercises (type, statement, solution) VALUES (102, '5+4', '9');
INSERT INTO exercises (type, statement, solution) VALUES (102, '10-8', '2');
INSERT INTO exercises (type, statement, solution) VALUES (102, '8+7', '15');
INSERT INTO exercises (type, statement, solution) VALUES (102, '8-8', '0');
INSERT INTO exercises (type, statement, solution) VALUES (102, '5+1', '6');
INSERT INTO exercises (type, statement, solution) VALUES (102, '10-0', '10');
INSERT INTO exercises (type, statement, solution) VALUES (102, '0:5', '0');
INSERT INTO exercises (type, statement, solution) VALUES (102, '5 \\times 4', '20');
INSERT INTO exercises (type, statement, solution) VALUES (102, '32:8', '4');
INSERT INTO exercises (type, statement, solution) VALUES (102, '2-2', '0');
INSERT INTO exercises (type, statement, solution) VALUES (102, '12-8', '4');
INSERT INTO exercises (type, statement, solution) VALUES (102, '4-2', '2');
INSERT INTO exercises (type, statement, solution) VALUES (102, '2+0', '2');
INSERT INTO exercises (type, statement, solution) VALUES (102, '14-13', '1');
INSERT INTO exercises (type, statement, solution) VALUES (102, '6:3', '2');
INSERT INTO exercises (type, statement, solution) VALUES (102, '13-4', '9');
INSERT INTO exercises (type, statement, solution) VALUES (102, '3+10', '13');
INSERT INTO exercises (type, statement, solution) VALUES (102, '9:9', '1');
INSERT INTO exercises (type, statement, solution) VALUES (102, '6 \\times 2', '12');
INSERT INTO exercises (type, statement, solution) VALUES (102, '10 \\times 10', '100');
INSERT INTO exercises (type, statement, solution) VALUES (102, '4:1', '4');
INSERT INTO exercises (type, statement, solution) VALUES (102, '48:8', '6');
INSERT INTO exercises (type, statement, solution) VALUES (102, '1 \\times 9', '9');
INSERT INTO exercises (type, statement, solution) VALUES (102, '10:10', '1');
INSERT INTO exercises (type, statement, solution) VALUES (102, '9 \\times 8', '72');
INSERT INTO exercises (type, statement, solution) VALUES (102, '9 \\times 10', '90');
INSERT INTO exercises (type, statement, solution) VALUES (102, '7 \\times 9', '63');
INSERT INTO exercises (type, statement, solution) VALUES (102, '9-1', '8');
INSERT INTO exercises (type, statement, solution) VALUES (102, '10-2', '8');
INSERT INTO exercises (type, statement, solution) VALUES (102, '21:3', '7');
INSERT INTO exercises (type, statement, solution) VALUES (102, '10+8', '18');
INSERT INTO exercises (type, statement, solution) VALUES (102, '10 \\times 4', '40');
INSERT INTO exercises (type, statement, solution) VALUES (102, '6+2', '8');
INSERT INTO exercises (type, statement, solution) VALUES (102, '3 \\times 5', '15');
INSERT INTO exercises (type, statement, solution) VALUES (102, '4 \\times 7', '28');
INSERT INTO exercises (type, statement, solution) VALUES (102, '3-3', '0');
INSERT INTO exercises (type, statement, solution) VALUES (102, '13-9', '4');
INSERT INTO exercises (type, statement, solution) VALUES (102, '4+8', '12');
INSERT INTO exercises (type, statement, solution) VALUES (102, '7:7', '1');
INSERT INTO exercises (type, statement, solution) VALUES (102, '3+9', '12');
INSERT INTO exercises (type, statement, solution) VALUES (102, '5+6', '11');
INSERT INTO exercises (type, statement, solution) VALUES (102, '9 \\times 4', '36');
INSERT INTO exercises (type, statement, solution) VALUES (102, '24:4', '6');
INSERT INTO exercises (type, statement, solution) VALUES (102, '6+1', '7');
INSERT INTO exercises (type, statement, solution) VALUES (102, '12-12', '0');
INSERT INTO exercises (type, statement, solution) VALUES (102, '9+6', '15');
INSERT INTO exercises (type, statement, solution) VALUES (102, '12-1', '11');
INSERT INTO exercises (type, statement, solution) VALUES (102, '1 \\times 6', '6');
INSERT INTO exercises (type, statement, solution) VALUES (102, '13-0', '13');
INSERT INTO exercises (type, statement, solution) VALUES (102, '1 \\times 7', '7');
INSERT INTO exercises (type, statement, solution) VALUES (102, '4 \\times 8', '32');
INSERT INTO exercises (type, statement, solution) VALUES (102, '12-0', '12');
INSERT INTO exercises (type, statement, solution) VALUES (102, '0:3', '0');
INSERT INTO exercises (type, statement, solution) VALUES (102, '5 \\times 7', '35');
INSERT INTO exercises (type, statement, solution) VALUES (102, '5-0', '5');
INSERT INTO exercises (type, statement, solution) VALUES (102, '4+7', '11');
INSERT INTO exercises (type, statement, solution) VALUES (102, '9-2', '7');
INSERT INTO exercises (type, statement, solution) VALUES (102, '9-3', '6');
INSERT INTO exercises (type, statement, solution) VALUES (102, '54:6', '9');
INSERT INTO exercises (type, statement, solution) VALUES (102, '42:7', '6');
INSERT INTO exercises (type, statement, solution) VALUES (102, '2 \\times 8', '16');
INSERT INTO exercises (type, statement, solution) VALUES (102, '6-6', '0');
INSERT INTO exercises (type, statement, solution) VALUES (102, '6+0', '6');
INSERT INTO exercises (type, statement, solution) VALUES (102, '54:9', '6');
INSERT INTO exercises (type, statement, solution) VALUES (102, '2 \\times 5', '10');
INSERT INTO exercises (type, statement, solution) VALUES (102, '3+7', '10');
INSERT INTO exercises (type, statement, solution) VALUES (102, '8 \\times 1', '8');
INSERT INTO exercises (type, statement, solution) VALUES (102, '14-8', '6');
INSERT INTO exercises (type, statement, solution) VALUES (102, '8-7', '1');
INSERT INTO exercises (type, statement, solution) VALUES (102, '10+10', '20');
INSERT INTO exercises (type, statement, solution) VALUES (102, '8 \\times 3', '24');
INSERT INTO exercises (type, statement, solution) VALUES (102, '10 \\times 8', '80');
INSERT INTO exercises (type, statement, solution) VALUES (102, '8-3', '5');
INSERT INTO exercises (type, statement, solution) VALUES (102, '56:8', '7');
INSERT INTO exercises (type, statement, solution) VALUES (102, '7 \\times 8', '56');
INSERT INTO exercises (type, statement, solution) VALUES (102, '13-5', '8');
INSERT INTO exercises (type, statement, solution) VALUES (102, '2+1', '3');
INSERT INTO exercises (type, statement, solution) VALUES (102, '5-1', '4');
INSERT INTO exercises (type, statement, solution) VALUES (102, '24:6', '4');
INSERT INTO exercises (type, statement, solution) VALUES (102, '7-4', '3');
INSERT INTO exercises (type, statement, solution) VALUES (102, '0+0', '0');
INSERT INTO exercises (type, statement, solution) VALUES (102, '9-0', '9');
INSERT INTO exercises (type, statement, solution) VALUES (102, '14-4', '10');
INSERT INTO exercises (type, statement, solution) VALUES (102, '6+4', '10');
INSERT INTO exercises (type, statement, solution) VALUES (102, '14-14', '0');
INSERT INTO exercises (type, statement, solution) VALUES (102, '21:7', '3');
INSERT INTO exercises (type, statement, solution) VALUES (102, '6+8', '14');
INSERT INTO exercises (type, statement, solution) VALUES (102, '6 \\times 6', '36');
INSERT INTO exercises (type, statement, solution) VALUES (102, '6+3', '9');
INSERT INTO exercises (type, statement, solution) VALUES (102, '2:2', '1');
INSERT INTO exercises (type, statement, solution) VALUES (102, '2-1', '1');
INSERT INTO exercises (type, statement, solution) VALUES (102, '6-0', '6');
INSERT INTO exercises (type, statement, solution) VALUES (102, '11-6', '5');
INSERT INTO exercises (type, statement, solution) VALUES (102, '15:5', '3');
INSERT INTO exercises (type, statement, solution) VALUES (102, '13-8', '5');
INSERT INTO exercises (type, statement, solution) VALUES (102, '9-5', '4');
INSERT INTO exercises (type, statement, solution) VALUES (102, '8+10', '18');
INSERT INTO exercises (type, statement, solution) VALUES (102, '13-12', '1');
INSERT INTO exercises (type, statement, solution) VALUES (102, '4 \\times 3', '12');
INSERT INTO exercises (type, statement, solution) VALUES (102, '1+3', '4');
INSERT INTO exercises (type, statement, solution) VALUES (102, '9-4', '5');
INSERT INTO exercises (type, statement, solution) VALUES (102, '13-10', '3');
INSERT INTO exercises (type, statement, solution) VALUES (102, '10-6', '4');
INSERT INTO exercises (type, statement, solution) VALUES (102, '2+5', '7');
INSERT INTO exercises (type, statement, solution) VALUES (102, '1 \\times 4', '4');
INSERT INTO exercises (type, statement, solution) VALUES (102, '10:1', '10');
INSERT INTO exercises (type, statement, solution) VALUES (102, '13-13', '0');
INSERT INTO exercises (type, statement, solution) VALUES (102, '10:2', '5');
INSERT INTO exercises (type, statement, solution) VALUES (102, '8-1', '7');
INSERT INTO exercises (type, statement, solution) VALUES (102, '2+3', '5');
INSERT INTO exercises (type, statement, solution) VALUES (102, '5+8', '13');
INSERT INTO exercises (type, statement, solution) VALUES (102, '5 \\times 1', '5');
INSERT INTO exercises (type, statement, solution) VALUES (102, '16:8', '2');
INSERT INTO exercises (type, statement, solution) VALUES (102, '11-9', '2');
INSERT INTO exercises (type, statement, solution) VALUES (102, '2-0', '2');
INSERT INTO exercises (type, statement, solution) VALUES (102, '5 \\times 9', '45');
INSERT INTO exercises (type, statement, solution) VALUES (102, '3 \\times 8', '24');
INSERT INTO exercises (type, statement, solution) VALUES (102, '12-4', '8');
INSERT INTO exercises (type, statement, solution) VALUES (102, '12-2', '10');
INSERT INTO exercises (type, statement, solution) VALUES (102, '12-10', '2');
INSERT INTO exercises (type, statement, solution) VALUES (102, '13-7', '6');
INSERT INTO exercises (type, statement, solution) VALUES (102, '0+10', '10');
INSERT INTO exercises (type, statement, solution) VALUES (102, '6 \\times 1', '6');
INSERT INTO exercises (type, statement, solution) VALUES (102, '7:1', '7');
INSERT INTO exercises (type, statement, solution) VALUES (102, '3+6', '9');
INSERT INTO exercises (type, statement, solution) VALUES (102, '10-9', '1');
INSERT INTO exercises (type, statement, solution) VALUES (102, '5-5', '0');
INSERT INTO exercises (type, statement, solution) VALUES (102, '7 \\times 4', '28');
INSERT INTO exercises (type, statement, solution) VALUES (102, '3+8', '11');
INSERT INTO exercises (type, statement, solution) VALUES (102, '1+7', '8');
INSERT INTO exercises (type, statement, solution) VALUES (102, '3:1', '3');
INSERT INTO exercises (type, statement, solution) VALUES (102, '2 \\times 1', '2');
INSERT INTO exercises (type, statement, solution) VALUES (102, '1-0', '1');
INSERT INTO exercises (type, statement, solution) VALUES (102, '12-3', '9');
INSERT INTO exercises (type, statement, solution) VALUES (102, '80:10', '8');
INSERT INTO exercises (type, statement, solution) VALUES (102, '3+4', '7');
INSERT INTO exercises (type, statement, solution) VALUES (102, '14-0', '14');
INSERT INTO exercises (type, statement, solution) VALUES (102, '11-1', '10');
INSERT INTO exercises (type, statement, solution) VALUES (102, '11-4', '7');
INSERT INTO exercises (type, statement, solution) VALUES (102, '6 \\times 8', '48');
INSERT INTO exercises (type, statement, solution) VALUES (102, '5+10', '15');
INSERT INTO exercises (type, statement, solution) VALUES (102, '30:10', '3');
INSERT INTO exercises (type, statement, solution) VALUES (102, '15:3', '5');
INSERT INTO exercises (type, statement, solution) VALUES (102, '10-5', '5');
INSERT INTO exercises (type, statement, solution) VALUES (102, '5 \\times 8', '40');
INSERT INTO exercises (type, statement, solution) VALUES (102, '5:5', '1');
INSERT INTO exercises (type, statement, solution) VALUES (102, '6-1', '5');
INSERT INTO exercises (type, statement, solution) VALUES (102, '0+6', '6');
INSERT INTO exercises (type, statement, solution) VALUES (102, '7-1', '6');
INSERT INTO exercises (type, statement, solution) VALUES (102, '35:5', '7');
INSERT INTO exercises (type, statement, solution) VALUES (102, '9+3', '12');
INSERT INTO exercises (type, statement, solution) VALUES (102, '9+10', '19');
INSERT INTO exercises (type, statement, solution) VALUES (102, '6 \\times 3', '18');
INSERT INTO exercises (type, statement, solution) VALUES (102, '12-9', '3');
INSERT INTO exercises (type, statement, solution) VALUES (102, '0+2', '2');
INSERT INTO exercises (type, statement, solution) VALUES (102, '0+7', '7');
INSERT INTO exercises (type, statement, solution) VALUES (102, '6 \\times 10', '60');
INSERT INTO exercises (type, statement, solution) VALUES (102, '7-3', '4');
INSERT INTO exercises (type, statement, solution) VALUES (102, '5+7', '12');
INSERT INTO exercises (type, statement, solution) VALUES (102, '11-10', '1');
INSERT INTO exercises (type, statement, solution) VALUES (102, '0:9', '0');
INSERT INTO exercises (type, statement, solution) VALUES (102, '7-7', '0');
INSERT INTO exercises (type, statement, solution) VALUES (102, '3+2', '5');
INSERT INTO exercises (type, statement, solution) VALUES (102, '24:8', '3');
INSERT INTO exercises (type, statement, solution) VALUES (102, '2+2', '4');
INSERT INTO exercises (type, statement, solution) VALUES (102, '4-4', '0');
INSERT INTO exercises (type, statement, solution) VALUES (102, '18:3', '6');
INSERT INTO exercises (type, statement, solution) VALUES (102, '40:4', '10');
INSERT INTO exercises (type, statement, solution) VALUES (102, '1 \\times 8', '8');
INSERT INTO exercises (type, statement, solution) VALUES (102, '4:4', '1');
INSERT INTO exercises (type, statement, solution) VALUES (102, '4 \\times 6', '24');
INSERT INTO exercises (type, statement, solution) VALUES (102, '8+1', '9');
INSERT INTO exercises (type, statement, solution) VALUES (102, '7 \\times 10', '70');
INSERT INTO exercises (type, statement, solution) VALUES (102, '4 \\times 10', '40');
INSERT INTO exercises (type, statement, solution) VALUES (102, '63:7', '9');
INSERT INTO exercises (type, statement, solution) VALUES (102, '9-8', '1');
INSERT INTO exercises (type, statement, solution) VALUES (102, '36:4', '9');
INSERT INTO exercises (type, statement, solution) VALUES (102, '3+0', '3');
INSERT INTO exercises (type, statement, solution) VALUES (102, '1 \\times 5', '5');
INSERT INTO exercises (type, statement, solution) VALUES (102, '7 \\times 3', '21');
INSERT INTO exercises (type, statement, solution) VALUES (102, '6-3', '3');
INSERT INTO exercises (type, statement, solution) VALUES (102, '11-5', '6');
INSERT INTO exercises (type, statement, solution) VALUES (102, '6+9', '15');
INSERT INTO exercises (type, statement, solution) VALUES (102, '3-2', '1');
INSERT INTO exercises (type, statement, solution) VALUES (102, '3 \\times 10', '30');
INSERT INTO exercises (type, statement, solution) VALUES (102, '2 \\times 2', '4');
INSERT INTO exercises (type, statement, solution) VALUES (102, '5-3', '2');
INSERT INTO exercises (type, statement, solution) VALUES (102, '3+5', '8');
INSERT INTO exercises (type, statement, solution) VALUES (102, '1+2', '3');
INSERT INTO exercises (type, statement, solution) VALUES (102, '9 \\times 2', '18');
INSERT INTO exercises (type, statement, solution) VALUES (102, '4 \\times 5', '20');
INSERT INTO exercises (type, statement, solution) VALUES (102, '20:4', '5');
INSERT INTO exercises (type, statement, solution) VALUES (102, '8-2', '6');
INSERT INTO exercises (type, statement, solution) VALUES (102, '7+10', '17');
INSERT INTO exercises (type, statement, solution) VALUES (102, '3-1', '2');
INSERT INTO exercises (type, statement, solution) VALUES (102, '8+6', '14');
INSERT INTO exercises (type, statement, solution) VALUES (102, '0+3', '3');
INSERT INTO exercises (type, statement, solution) VALUES (102, '6 \\times 4', '24');
INSERT INTO exercises (type, statement, solution) VALUES (102, '18:2', '9');
INSERT INTO exercises (type, statement, solution) VALUES (102, '9-6', '3');
INSERT INTO exercises (type, statement, solution) VALUES (102, '7 \\times 5', '35');
INSERT INTO exercises (type, statement, solution) VALUES (102, '0:8', '0');
INSERT INTO exercises (type, statement, solution) VALUES (102, '4+10', '14');
INSERT INTO exercises (type, statement, solution) VALUES (102, '72:9', '8');
INSERT INTO exercises (type, statement, solution) VALUES (102, '3 \\times 1', '3');
INSERT INTO exercises (type, statement, solution) VALUES (102, '20:10', '2');
INSERT INTO exercises (type, statement, solution) VALUES (102, '12-5', '7');
INSERT INTO exercises (type, statement, solution) VALUES (102, '90:9', '10');
INSERT INTO exercises (type, statement, solution) VALUES (102, '1+8', '9');
INSERT INTO exercises (type, statement, solution) VALUES (102, '10+2', '12');
INSERT INTO exercises (type, statement, solution) VALUES (102, '12-6', '6');
INSERT INTO exercises (type, statement, solution) VALUES (102, '5-2', '3');
INSERT INTO exercises (type, statement, solution) VALUES (102, '1+6', '7');
INSERT INTO exercises (type, statement, solution) VALUES (102, '7 \\times 7', '49');
INSERT INTO exercises (type, statement, solution) VALUES (102, '30:3', '10');
INSERT INTO exercises (type, statement, solution) VALUES (102, '14-10', '4');
INSERT INTO exercises (type, statement, solution) VALUES (102, '1 \\times 2', '2');
INSERT INTO exercises (type, statement, solution) VALUES (102, '0+4', '4');
INSERT INTO exercises (type, statement, solution) VALUES (102, '2 \\times 7', '14');
INSERT INTO exercises (type, statement, solution) VALUES (102, '8+8', '16');
INSERT INTO exercises (type, statement, solution) VALUES (102, '40:5', '8');
INSERT INTO exercises (type, statement, solution) VALUES (102, '18:9', '2');
INSERT INTO exercises (type, statement, solution) VALUES (102, '9+5', '14');
INSERT INTO exercises (type, statement, solution) VALUES (102, '8+2', '10');
INSERT INTO exercises (type, statement, solution) VALUES (102, '11-11', '0');
INSERT INTO exercises (type, statement, solution) VALUES (102, '9-7', '2');
INSERT INTO exercises (type, statement, solution) VALUES (102, '2 \\times 6', '12');
INSERT INTO exercises (type, statement, solution) VALUES (102, '9 \\times 5', '45');
INSERT INTO exercises (type, statement, solution) VALUES (102, '4+5', '9');
INSERT INTO exercises (type, statement, solution) VALUES (102, '7+4', '11');
INSERT INTO exercises (type, statement, solution) VALUES (102, '3 \\times 3', '9');
INSERT INTO exercises (type, statement, solution) VALUES (102, '0+5', '5');
INSERT INTO exercises (type, statement, solution) VALUES (102, '2+4', '6');
INSERT INTO exercises (type, statement, solution) VALUES (102, '5-4', '1');
INSERT INTO exercises (type, statement, solution) VALUES (102, '3 \\times 6', '18');
INSERT INTO exercises (type, statement, solution) VALUES (102, '0:1', '0');
INSERT INTO exercises (type, statement, solution) VALUES (102, '4-0', '4');
INSERT INTO exercises (type, statement, solution) VALUES (102, '4 \\times 4', '16');
INSERT INTO exercises (type, statement, solution) VALUES (102, '10-4', '6');
INSERT INTO exercises (type, statement, solution) VALUES (102, '10 \\times 3', '30');
INSERT INTO exercises (type, statement, solution) VALUES (102, '4+6', '10');
INSERT INTO exercises (type, statement, solution) VALUES (102, '10 \\times 7', '70');
INSERT INTO exercises (type, statement, solution) VALUES (102, '7+3', '10');
INSERT INTO exercises (type, statement, solution) VALUES (102, '8:8', '1');
INSERT INTO exercises (type, statement, solution) VALUES (102, '14-3', '11');
INSERT INTO exercises (type, statement, solution) VALUES (102, '28:7', '4');
INSERT INTO exercises (type, statement, solution) VALUES (102, '40:10', '4');
INSERT INTO exercises (type, statement, solution) VALUES (102, '2+8', '10');
INSERT INTO exercises (type, statement, solution) VALUES (102, '27:9', '3');
INSERT INTO exercises (type, statement, solution) VALUES (102, '14:2', '7');
INSERT INTO exercises (type, statement, solution) VALUES (102, '9 \\times 7', '63');
INSERT INTO exercises (type, statement, solution) VALUES (102, '13-3', '10');
INSERT INTO exercises (type, statement, solution) VALUES (102, '3 \\times 4', '12');
INSERT INTO exercises (type, statement, solution) VALUES (102, '9:1', '9');
INSERT INTO exercises (type, statement, solution) VALUES (102, '12:6', '2');
INSERT INTO exercises (type, statement, solution) VALUES (102, '8:2', '4');
INSERT INTO exercises (type, statement, solution) VALUES (102, '8 \\times 6', '48');
INSERT INTO exercises (type, statement, solution) VALUES (102, '8 \\times 2', '16');
INSERT INTO exercises (type, statement, solution) VALUES (102, '7+1', '8');
INSERT INTO exercises (type, statement, solution) VALUES (102, '3 \\times 7', '21');
INSERT INTO exercises (type, statement, solution) VALUES (102, '7+8', '15');
INSERT INTO exercises (type, statement, solution) VALUES (102, '16:2', '8');
INSERT INTO exercises (type, statement, solution) VALUES (102, '14-12', '2');
INSERT INTO exercises (type, statement, solution) VALUES (102, '35:7', '5');
INSERT INTO exercises (type, statement, solution) VALUES (102, '11-2', '9');
INSERT INTO exercises (type, statement, solution) VALUES (102, '13-1', '12');
INSERT INTO exercises (type, statement, solution) VALUES (102, '12:2', '6');
INSERT INTO exercises (type, statement, solution) VALUES (102, '9+9', '18');
INSERT INTO exercises (type, statement, solution) VALUES (102, '4+0', '4');
INSERT INTO exercises (type, statement, solution) VALUES (102, '8 \\times 10', '80');
INSERT INTO exercises (type, statement, solution) VALUES (102, '14-5', '9');
INSERT INTO exercises (type, statement, solution) VALUES (102, '6-2', '4');
INSERT INTO exercises (type, statement, solution) VALUES (102, '10 \\times 1', '10');
INSERT INTO exercises (type, statement, solution) VALUES (102, '45:5', '9');
INSERT INTO exercises (type, statement, solution) VALUES (102, '10+3', '13');
INSERT INTO exercises (type, statement, solution) VALUES (102, '12-11', '1');
INSERT INTO exercises (type, statement, solution) VALUES (102, '30:6', '5');
INSERT INTO exercises (type, statement, solution) VALUES (102, '8+0', '8');
INSERT INTO exercises (type, statement, solution) VALUES (102, '1 \\times 10', '10');
INSERT INTO exercises (type, statement, solution) VALUES (102, '14-2', '12');
INSERT INTO exercises (type, statement, solution) VALUES (102, '5 \\times 2', '10');
INSERT INTO exercises (type, statement, solution) VALUES (102, '7-2', '5');
INSERT INTO exercises (type, statement, solution) VALUES (102, '13-6', '7');
INSERT INTO exercises (type, statement, solution) VALUES (102, '9+2', '11');
INSERT INTO exercises (type, statement, solution) VALUES (102, '3 \\times 9', '27');
INSERT INTO exercises (type, statement, solution) VALUES (102, '10+7', '17');
INSERT INTO exercises (type, statement, solution) VALUES (102, '45:9', '5');
INSERT INTO exercises (type, statement, solution) VALUES (102, '7 \\times 2', '14');
INSERT INTO exercises (type, statement, solution) VALUES (102, '10-3', '7');
INSERT INTO exercises (type, statement, solution) VALUES (102, '8:1', '8');
INSERT INTO exercises (type, statement, solution) VALUES (102, '5 \\times 5', '25');
INSERT INTO exercises (type, statement, solution) VALUES (102, '0:7', '0');
INSERT INTO exercises (type, statement, solution) VALUES (102, '11-3', '8');
INSERT INTO exercises (type, statement, solution) VALUES (102, '20:2', '10');
INSERT INTO exercises (type, statement, solution) VALUES (102, '5 \\times 10', '50');
INSERT INTO exercises (type, statement, solution) VALUES (102, '50:10', '5');
INSERT INTO exercises (type, statement, solution) VALUES (102, '1+0', '1');
INSERT INTO exercises (type, statement, solution) VALUES (102, '28:4', '7');
INSERT INTO exercises (type, statement, solution) VALUES (102, '4+1', '5');
INSERT INTO exercises (type, statement, solution) VALUES (102, '0+8', '8');
INSERT INTO exercises (type, statement, solution) VALUES (102, '10 \\times 9', '90');
INSERT INTO exercises (type, statement, solution) VALUES (102, '42:6', '7');
INSERT INTO exercises (type, statement, solution) VALUES (102, '7 \\times 6', '42');
INSERT INTO exercises (type, statement, solution) VALUES (102, '4-1', '3');
INSERT INTO exercises (type, statement, solution) VALUES (102, '3+3', '6');
INSERT INTO exercises (type, statement, solution) VALUES (102, '14-1', '13');
INSERT INTO exercises (type, statement, solution) VALUES (102, '40:8', '5');
INSERT INTO exercises (type, statement, solution) VALUES (102, '9+1', '10');
INSERT INTO exercises (type, statement, solution) VALUES (102, '9+8', '17');
INSERT INTO exercises (type, statement, solution) VALUES (102, '18:6', '3');
INSERT INTO exercises (type, statement, solution) VALUES (102, '8 \\times 9', '72');
INSERT INTO exercises (type, statement, solution) VALUES (102, '4+2', '6');
INSERT INTO exercises (type, statement, solution) VALUES (102, '5 \\times 3', '15');
INSERT INTO exercises (type, statement, solution) VALUES (102, '4+9', '13');
INSERT INTO exercises (type, statement, solution) VALUES (102, '72:8', '9');
INSERT INTO exercises (type, statement, solution) VALUES (102, '48:6', '8');
INSERT INTO exercises (type, statement, solution) VALUES (102, '2+10', '12');
INSERT INTO exercises (type, statement, solution) VALUES (102, '2 \\times 3', '6');
INSERT INTO exercises (type, statement, solution) VALUES (102, '5+5', '10');
INSERT INTO exercises (type, statement, solution) VALUES (102, '12-7', '5');
INSERT INTO exercises (type, statement, solution) VALUES (102, '2+9', '11');
INSERT INTO exercises (type, statement, solution) VALUES (102, '7+9', '16');
INSERT INTO exercises (type, statement, solution) VALUES (102, '2 \\times 9', '18');
INSERT INTO exercises (type, statement, solution) VALUES (102, '9 \\times 1', '9');
INSERT INTO exercises (type, statement, solution) VALUES (102, '8 \\times 7', '56');
INSERT INTO exercises (type, statement, solution) VALUES (102, '7-5', '2');
INSERT INTO exercises (type, statement, solution) VALUES (102, '8-5', '3');
INSERT INTO exercises (type, statement, solution) VALUES (102, '30:5', '6');
INSERT INTO exercises (type, statement, solution) VALUES (102, '8 \\times 4', '32');
INSERT INTO exercises (type, statement, solution) VALUES (102, '63:9', '7');
INSERT INTO exercises (type, statement, solution) VALUES (102, '36:9', '4');
INSERT INTO exercises (type, statement, solution) VALUES (102, '13-11', '2');
INSERT INTO exercises (type, statement, solution) VALUES (102, '24:3', '8');
INSERT INTO exercises (type, statement, solution) VALUES (102, '1+1', '2');
INSERT INTO exercises (type, statement, solution) VALUES (102, '1 \\times 3', '3');
INSERT INTO exercises (type, statement, solution) VALUES (102, '8 \\times 5', '40');
INSERT INTO exercises (type, statement, solution) VALUES (102, '3:3', '1');
INSERT INTO exercises (type, statement, solution) VALUES (102, '8+5', '13');
INSERT INTO exercises (type, statement, solution) VALUES (102, '14-6', '8');
INSERT INTO exercises (type, statement, solution) VALUES (102, '7 \\times 1', '7');
INSERT INTO exercises (type, statement, solution) VALUES (102, '10 \\times 6', '60');
INSERT INTO exercises (type, statement, solution) VALUES (102, '6:6', '1');
INSERT INTO exercises (type, statement, solution) VALUES (102, '7+6', '13');
INSERT INTO exercises (type, statement, solution) VALUES (102, '5+3', '8');
INSERT INTO exercises (type, statement, solution) VALUES (102, '8+4', '12');
INSERT INTO exercises (type, statement, solution) VALUES (102, '5 \\times 6', '30');
INSERT INTO exercises (type, statement, solution) VALUES (102, '10+1', '11');
INSERT INTO exercises (type, statement, solution) VALUES (102, '10 \\times 5', '50');
INSERT INTO exercises (type, statement, solution) VALUES (102, '3+1', '4');
INSERT INTO exercises (type, statement, solution) VALUES (102, '4+4', '8');
INSERT INTO exercises (type, statement, solution) VALUES (102, '70:10', '7');
INSERT INTO exercises (type, statement, solution) VALUES (102, '8-6', '2');
INSERT INTO exercises (type, statement, solution) VALUES (102, '8 \\times 8', '64');
INSERT INTO exercises (type, statement, solution) VALUES (102, '56:7', '8');
INSERT INTO exercises (type, statement, solution) VALUES (102, '6 \\times 5', '30');
INSERT INTO exercises (type, statement, solution) VALUES (102, '70:7', '10');
INSERT INTO exercises (type, statement, solution) VALUES (102, '1+10', '11');
INSERT INTO exercises (type, statement, solution) VALUES (102, '9 \\times 6', '54');
INSERT INTO exercises (type, statement, solution) VALUES (102, '1+5', '6');
INSERT INTO exercises (type, statement, solution) VALUES (102, '9 \\times 9', '81');
INSERT INTO exercises (type, statement, solution) VALUES (102, '6+10', '16');
INSERT INTO exercises (type, statement, solution) VALUES (102, '4-3', '1');
INSERT INTO exercises (type, statement, solution) VALUES (102, '4 \\times 1', '4');
INSERT INTO exercises (type, statement, solution) VALUES (102, '7-0', '7');
INSERT INTO exercises (type, statement, solution) VALUES (102, '1+4', '5');
INSERT INTO exercises (type, statement, solution) VALUES (102, '8:4', '2');
INSERT INTO exercises (type, statement, solution) VALUES (102, '6 \\times 9', '54');
INSERT INTO exercises (type, statement, solution) VALUES (102, '80:8', '10');
INSERT INTO exercises (type, statement, solution) VALUES (102, '0:4', '0');
INSERT INTO exercises (type, statement, solution) VALUES (102, '1+9', '10');
INSERT INTO exercises (type, statement, solution) VALUES (102, '6:1', '6');
INSERT INTO exercises (type, statement, solution) VALUES (102, '1-1', '0');
INSERT INTO exercises (type, statement, solution) VALUES (102, '27:3', '9');
INSERT INTO exercises (type, statement, solution) VALUES (102, '2 \\times 10', '20');
INSERT INTO exercises (type, statement, solution) VALUES (102, '4 \\times 2', '8');
INSERT INTO exercises (type, statement, solution) VALUES (102, '6+5', '11');
INSERT INTO exercises (type, statement, solution) VALUES (102, '2 \\times 4', '8');
INSERT INTO exercises (type, statement, solution) VALUES (102, '14-11', '3');
INSERT INTO exercises (type, statement, solution) VALUES (102, '11-7', '4');
INSERT INTO exercises (type, statement, solution) VALUES (102, '7+2', '9');
INSERT INTO exercises (type, statement, solution) VALUES (102, '0:2', '0');
INSERT INTO exercises (type, statement, solution) VALUES (102, '11-8', '3');
INSERT INTO exercises (type, statement, solution) VALUES (102, '9+7', '16');
INSERT INTO exercises (type, statement, solution) VALUES (102, '8+3', '11');
INSERT INTO exercises (type, statement, solution) VALUES (102, '8-4', '4');
INSERT INTO exercises (type, statement, solution) VALUES (102, '7+0', '7');
INSERT INTO exercises (type, statement, solution) VALUES (102, '7+5', '12');
INSERT INTO exercises (type, statement, solution) VALUES (102, '8+9', '17');
INSERT INTO exercises (type, statement, solution) VALUES (102, '10-1', '9');
INSERT INTO exercises (type, statement, solution) VALUES (102, '2:1', '2');
INSERT INTO exercises (type, statement, solution) VALUES (102, '90:10', '9');
INSERT INTO exercises (type, statement, solution) VALUES (102, '10+4', '14');
INSERT INTO exercises (type, statement, solution) VALUES (102, '5+2', '7');
INSERT INTO exercises (type, statement, solution) VALUES (102, '10 \\times 2', '20');
INSERT INTO exercises (type, statement, solution) VALUES (102, '13-2', '11');
INSERT INTO exercises (type, statement, solution) VALUES (102, '10-7', '3');
INSERT INTO exercises (type, statement, solution) VALUES (102, '5:1', '5');
INSERT INTO exercises (type, statement, solution) VALUES (102, '5+9', '14');
INSERT INTO exercises (type, statement, solution) VALUES (102, '1 \\times 1', '1');
INSERT INTO exercises (type, statement, solution) VALUES (102, '0:10', '0');
INSERT INTO exercises (type, statement, solution) VALUES (102, '6-4', '2');
INSERT INTO exercises (type, statement, solution) VALUES (102, '6-5', '1');
INSERT INTO exercises (type, statement, solution) VALUES (102, '6+6', '12');
INSERT INTO exercises (type, statement, solution) VALUES (102, '10+0', '10');
INSERT INTO exercises (type, statement, solution) VALUES (102, '10+6', '16');
INSERT INTO exercises (type, statement, solution) VALUES (102, '0+9', '9');
INSERT INTO exercises (type, statement, solution) VALUES (102, '50:5', '10');
INSERT INTO exercises (type, statement, solution) VALUES (102, '4+3', '7');
INSERT INTO exercises (type, statement, solution) VALUES (102, '7+7', '14');
INSERT INTO exercises (type, statement, solution) VALUES (102, '3-0', '3');
INSERT INTO exercises (type, statement, solution) VALUES (102, '7-6', '1');
INSERT INTO exercises (type, statement, solution) VALUES (102, '60:10', '6');
INSERT INTO exercises (type, statement, solution) VALUES (102, '6:2', '3');
INSERT INTO exercises (type, statement, solution) VALUES (102, '20:5', '4');
INSERT INTO exercises (type, statement, solution) VALUES (102, '8-0', '8');
INSERT INTO exercises (type, statement, solution) VALUES (102, '9+4', '13');
INSERT INTO exercises (type, statement, solution) VALUES (102, '11-0', '11');
INSERT INTO exercises (type, statement, solution) VALUES (102, '4 \\times 9', '36');
INSERT INTO exercises (type, statement, solution) VALUES (102, '2+6', '8');
