INSERT INTO exercises (type, statement, solution) VALUES (210, '5 - 9 \\cdot (-1) - 15', '-1');
INSERT INTO exercises (type, statement, solution) VALUES (210, '-1 + 4 - 5 + 1', '-1');
INSERT INTO exercises (type, statement, solution) VALUES (210, '3:(-3) - 2 \\cdot 2', '-5');
INSERT INTO exercises (type, statement, solution) VALUES (210, '-4:(2-6) -4', '-3');
INSERT INTO exercises (type, statement, solution) VALUES (210, '(-6+8) \\cdot (-1) + 5', '3');
INSERT INTO exercises (type, statement, solution) VALUES (210, '10:(-4-1) +6', '4');
INSERT INTO exercises (type, statement, solution) VALUES (210, '(-1-3) \\cdot (2 - 3)', '4');
INSERT INTO exercises (type, statement, solution) VALUES (210, '\\left[4 + (-7)\\right] : (- 5+4)', '3');
INSERT INTO exercises (type, statement, solution) VALUES (210, '-1 + (+4) - (-8)', '11');
INSERT INTO exercises (type, statement, solution) VALUES (210, '-5 \\cdot (-1 - 1) - 12', '-2');
INSERT INTO exercises (type, statement, solution) VALUES (210, '(-5 + 7) \\cdot (-4+1)', '-6');
INSERT INTO exercises (type, statement, solution) VALUES (210, '- 6:(-1-1) - 8', '-5');
INSERT INTO exercises (type, statement, solution) VALUES (210, '-4:2 -  2 \\cdot 1', '-4');
INSERT INTO exercises (type, statement, solution) VALUES (210, '4 - 6 \\cdot (-1) - 7', '3');
INSERT INTO exercises (type, statement, solution) VALUES (210, '-4 + (5-6) - 7', '-12');
INSERT INTO exercises (type, statement, solution) VALUES (210, '1 + 2 \\cdot 2 - 8', '-3');
INSERT INTO exercises (type, statement, solution) VALUES (210, '(-4 + 2) \\cdot (5 - 7)', '4');
INSERT INTO exercises (type, statement, solution) VALUES (210, '(-4 + 4 \\cdot 2) \\cdot (-2)', '-8');
INSERT INTO exercises (type, statement, solution) VALUES (210, '(-1 + 5) : (-4 + 2)', '-2');
INSERT INTO exercises (type, statement, solution) VALUES (210, '(-5 - 5) \\cdot 2 + 8', '-12');
INSERT INTO exercises (type, statement, solution) VALUES (210, '(-4 \\cdot 3 + 10) : (-1)', '2');
INSERT INTO exercises (type, statement, solution) VALUES (210, '(-4+5) \\cdot (-1-4)', '-5');
INSERT INTO exercises (type, statement, solution) VALUES (210, '5-7-1 \\cdot (-1)', '-1');
INSERT INTO exercises (type, statement, solution) VALUES (210, '10 : (-6+1) - (-4)', '2');
INSERT INTO exercises (type, statement, solution) VALUES (210, '\\left[5+(-4)\\right] \\cdot (-4 - 3)', '-7');
INSERT INTO exercises (type, statement, solution) VALUES (210, '5-8 \\cdot (-1) - 16', '-3');
INSERT INTO exercises (type, statement, solution) VALUES (210, '6 \\cdot (5 -8 - 2)', '-30');
INSERT INTO exercises (type, statement, solution) VALUES (210, '-8:(4 - 6) - 10', '-6');
INSERT INTO exercises (type, statement, solution) VALUES (210, '-(-1)+(-2)+(-3)-(-4)', '0');
INSERT INTO exercises (type, statement, solution) VALUES (210, '4 + 2 \\cdot (-4) - 1', '-5');
INSERT INTO exercises (type, statement, solution) VALUES (210, '-4 -5 -1 + 8', '-2');
INSERT INTO exercises (type, statement, solution) VALUES (210, '-4 \\cdot (1 - 5) - 10', '6');
INSERT INTO exercises (type, statement, solution) VALUES (210, '5+(-7) - 2 \\cdot (-2)', '2');
INSERT INTO exercises (type, statement, solution) VALUES (210, '-(-2 \\cdot 4) - 9 + 5', '4');
INSERT INTO exercises (type, statement, solution) VALUES (210, '12:(-4-2) + 9', '7');
INSERT INTO exercises (type, statement, solution) VALUES (210, '\\left[-5 - (-1 -2)\\right] \\cdot 5', '-10');
INSERT INTO exercises (type, statement, solution) VALUES (210, '-7+8:(-4) + 5', '-4');
INSERT INTO exercises (type, statement, solution) VALUES (210, '-6:(1-4) -8', '-6');
INSERT INTO exercises (type, statement, solution) VALUES (210, '4-(+5)+(-1) \\cdot 2', '-3');
INSERT INTO exercises (type, statement, solution) VALUES (210, '(-1+9):(-3-1)', '-2');
INSERT INTO exercises (type, statement, solution) VALUES (210, '7 \\cdot (-4+6) - 15', '-1');
INSERT INTO exercises (type, statement, solution) VALUES (210, '4:(-2-2) - 1', '-2');
INSERT INTO exercises (type, statement, solution) VALUES (210, '-1+5 \\cdot (-2) - 2', '-13');
INSERT INTO exercises (type, statement, solution) VALUES (210, '-7+(+8) -(-4) +(-7)', '-2');
INSERT INTO exercises (type, statement, solution) VALUES (210, '2 \\cdot (-1+4) - 7', '-1');
INSERT INTO exercises (type, statement, solution) VALUES (210, '\\left[-1 +(-4)\\right] \\cdot \\left[-4 - (-4)\\right]', '0');
INSERT INTO exercises (type, statement, solution) VALUES (210, '6:(-4+1)-10', '-12');
INSERT INTO exercises (type, statement, solution) VALUES (210, '-4 + (+2) - (2 - 5)', '1');
INSERT INTO exercises (type, statement, solution) VALUES (210, '4:(-5+1) \\cdot (-2)', '2');
INSERT INTO exercises (type, statement, solution) VALUES (210, '(-4 -1 \\cdot 5) : (-3)', '3');
INSERT INTO exercises (type, statement, solution) VALUES (210, '10:(-9+7) - 1', '-6');
INSERT INTO exercises (type, statement, solution) VALUES (210, '8-9 \\cdot 2 + 5', '-5');
INSERT INTO exercises (type, statement, solution) VALUES (210, '10:(-5) + 2 \\cdot (-2)', '-6');
INSERT INTO exercises (type, statement, solution) VALUES (210, '(9 - 10) \\cdot (-5 -1)', '6');
INSERT INTO exercises (type, statement, solution) VALUES (210, '-5 -(+ 5) + (-6 + 7)', '-9');
INSERT INTO exercises (type, statement, solution) VALUES (210, '7 - 4 \\cdot 2 + 9', '8');
INSERT INTO exercises (type, statement, solution) VALUES (210, '4 \\cdot (-5 + 3) + 4', '-4');
INSERT INTO exercises (type, statement, solution) VALUES (210, '-(+7) -1 \\cdot (-10) - 5', '-2');
INSERT INTO exercises (type, statement, solution) VALUES (210, '3 - 5 \\cdot 4 + 14', '-3');
INSERT INTO exercises (type, statement, solution) VALUES (210, '\\left[-(-6) - 7 \\cdot 2\\right] : (-4)', '2');
INSERT INTO exercises (type, statement, solution) VALUES (210, '4-6+(-1) \\cdot 4', '-6');
INSERT INTO exercises (type, statement, solution) VALUES (210, '6 - 8 \\cdot (-2) -10', '12');
INSERT INTO exercises (type, statement, solution) VALUES (210, '-5-\\left[4:(-2)\\right] - 10', '-13');
INSERT INTO exercises (type, statement, solution) VALUES (210, '\\left[-(+6) - (-2)\\right] : (5 - 7)', '2');
INSERT INTO exercises (type, statement, solution) VALUES (210, '\\left[5:(-5)-2\\right] + 7', '4');
INSERT INTO exercises (type, statement, solution) VALUES (210, '2-6 \\cdot 2 +3', '-7');
INSERT INTO exercises (type, statement, solution) VALUES (210, '5 - (6 - 9) - 9', '-1');
INSERT INTO exercises (type, statement, solution) VALUES (210, '6:(-1+4) - 6', '-4');
INSERT INTO exercises (type, statement, solution) VALUES (210, '\\left[6+(-8) - (-1)\\right] \\cdot 5', '-5');
INSERT INTO exercises (type, statement, solution) VALUES (210, '(6-9) \\cdot (7-10)', '9');
INSERT INTO exercises (type, statement, solution) VALUES (210, '(-4-4):(-2) \\cdot (-1)', '-4');
INSERT INTO exercises (type, statement, solution) VALUES (210, '-4-4:(-2) \\cdot (-1)', '-6');
INSERT INTO exercises (type, statement, solution) VALUES (210, '10 :(-4-1) - 5', '-7');
INSERT INTO exercises (type, statement, solution) VALUES (210, '\\left[(-8+6) - (-2)\\right] \\cdot 8', '0');
INSERT INTO exercises (type, statement, solution) VALUES (210, '8 : (-6-2) + 9', '8');
INSERT INTO exercises (type, statement, solution) VALUES (210, '\\left[-5 - (-1)\\right]:(-2-2)', '1');
INSERT INTO exercises (type, statement, solution) VALUES (210, '(6 -10) \\cdot (-1+6)', '-20');
INSERT INTO exercises (type, statement, solution) VALUES (210, '\\left[6 - (+9) - (-2)\\right] \\cdot (-1)', '1');
INSERT INTO exercises (type, statement, solution) VALUES (210, '8:(-4+2-6)', '-1');
INSERT INTO exercises (type, statement, solution) VALUES (210, '10:(-3-2) - 2', '-4');
INSERT INTO exercises (type, statement, solution) VALUES (210, '4 - 6 \\cdot 3 + 9', '-5');
INSERT INTO exercises (type, statement, solution) VALUES (210, '-8-6+(-2)+(+10)', '-6');
INSERT INTO exercises (type, statement, solution) VALUES (210, '5 \\cdot (-8+3) + 20', '-5');
INSERT INTO exercises (type, statement, solution) VALUES (210, '1+1 \\cdot (-1-2)', '-2');
INSERT INTO exercises (type, statement, solution) VALUES (210, '\\left[-(-4) - 5 \\cdot 2\\right]:(-2)', '3');
INSERT INTO exercises (type, statement, solution) VALUES (210, '\\left[-8 - (-6)\\right]:(8-10)', '1');
INSERT INTO exercises (type, statement, solution) VALUES (210, '(5 - 9): (-10+14)', '-1');
INSERT INTO exercises (type, statement, solution) VALUES (210, '- 1 - 1 -1 + 7', '4');
INSERT INTO exercises (type, statement, solution) VALUES (210, '8: (-7 +4 - 1)', '-2');
INSERT INTO exercises (type, statement, solution) VALUES (210, '-(-8) \\cdot (-1-1) + 9', '-7');
INSERT INTO exercises (type, statement, solution) VALUES (210, '-5 + (4 -7 \\cdot 2)', '-15');
INSERT INTO exercises (type, statement, solution) VALUES (210, '2 - (-5 -4) \\cdot (-1)', '-7');
INSERT INTO exercises (type, statement, solution) VALUES (210, '(-5 + 4) \\cdot (-8+2)', '6');
INSERT INTO exercises (type, statement, solution) VALUES (210, '(5 - 8 + 1) : 2', '-1');
INSERT INTO exercises (type, statement, solution) VALUES (210, '-10 : (-5) - 4 + 9', '7');
INSERT INTO exercises (type, statement, solution) VALUES (210, '6 : (-4-2) + 5', '4');
INSERT INTO exercises (type, statement, solution) VALUES (210, '-2 + \\left[4 \\cdot (-2)\\right] +16', '6');
INSERT INTO exercises (type, statement, solution) VALUES (210, '\\left[-5 - (+6) +1\\right] : (4+1)', '-2');
INSERT INTO exercises (type, statement, solution) VALUES (210, '(5-6):(-1+2)', '-1');
INSERT INTO exercises (type, statement, solution) VALUES (210, '(4-8) \\cdot  (-5 -1)', '24');
INSERT INTO exercises (type, statement, solution) VALUES (210, '5:(-4-1) -1', '-2');
INSERT INTO exercises (type, statement, solution) VALUES (210, '\\left[6:(-3) + 4\\right] \\cdot (-1)', '-2');
INSERT INTO exercises (type, statement, solution) VALUES (210, '-1-1+4-5', '-3');
INSERT INTO exercises (type, statement, solution) VALUES (210, '\\left[6-(-2)\\right]:(-2-2)', '-2');
INSERT INTO exercises (type, statement, solution) VALUES (210, '\\left[6-(-2):(-2)\\right] \\cdot (-2)', '-10');
INSERT INTO exercises (type, statement, solution) VALUES (210, '8 - 10 \\cdot 2 + 5', '-7');
INSERT INTO exercises (type, statement, solution) VALUES (210, '6:(-5-1) +6', '5');
INSERT INTO exercises (type, statement, solution) VALUES (210, '- 5 - (+2 - 8) : (-2)', '-8');
INSERT INTO exercises (type, statement, solution) VALUES (210, '4 \\cdot (-2-1) - 1', '-13');
INSERT INTO exercises (type, statement, solution) VALUES (210, '\\left[10 - (+11)\\right] \\cdot (-2 + 7)', '-5');
INSERT INTO exercises (type, statement, solution) VALUES (210, '-4 : (5 - 9) - 4', '-3');
INSERT INTO exercises (type, statement, solution) VALUES (210, '6 - ( -10 + 18) - 1', '-3');
INSERT INTO exercises (type, statement, solution) VALUES (210, '-5 - (+4- 6) - 1', '-4');
INSERT INTO exercises (type, statement, solution) VALUES (210, '(-7 +1) \\cdot (-3 - 3)', '36');
INSERT INTO exercises (type, statement, solution) VALUES (210, '-9 : 9 - 1 + 6', '4');
INSERT INTO exercises (type, statement, solution) VALUES (210, '8:(-7-1) +1', '0');
INSERT INTO exercises (type, statement, solution) VALUES (210, '\\left[5 - (-6) - 12\\right] \\cdot 8', '-8');
INSERT INTO exercises (type, statement, solution) VALUES (210, '\\left[-1 + (-8) +4\\right] \\cdot 3', '-15');
INSERT INTO exercises (type, statement, solution) VALUES (210, '(-5-5) : (4 -5)', '10');
INSERT INTO exercises (type, statement, solution) VALUES (210, '10:(-2-3) - 5', '-7');
INSERT INTO exercises (type, statement, solution) VALUES (210, '8:(-4) - (-1) - 1', '-2');
INSERT INTO exercises (type, statement, solution) VALUES (210, '4 \\cdot (-2) \\cdot 2 : (-8)', '2');
INSERT INTO exercises (type, statement, solution) VALUES (210, '2 - ( -4 +8) - 1', '-3');
INSERT INTO exercises (type, statement, solution) VALUES (210, '-6:(-6) + \\left[5 \\cdot (-2)\\right]', '-9');
INSERT INTO exercises (type, statement, solution) VALUES (210, '4 - 14 -8 \\cdot (-2)', '6');
INSERT INTO exercises (type, statement, solution) VALUES (210, '\\left[5 - (+2 - 9)\\right] : (-2)', '-6');
INSERT INTO exercises (type, statement, solution) VALUES (210, '- 7 - 2 \\cdot 2 + 4', '-7');
INSERT INTO exercises (type, statement, solution) VALUES (210, '- 4 \\cdot (-5 + 6) + 7', '3');
INSERT INTO exercises (type, statement, solution) VALUES (210, '-(+2) -1 \\cdot 4 + 5', '-1');
INSERT INTO exercises (type, statement, solution) VALUES (210, '2 - 4 \\cdot 6 + 14', '-8');
INSERT INTO exercises (type, statement, solution) VALUES (210, '\\left[-(-2) - 6 \\cdot 2\\right] : (-5)', '2');
INSERT INTO exercises (type, statement, solution) VALUES (210, '5:(-4-1)-10', '-11');
INSERT INTO exercises (type, statement, solution) VALUES (210, '-4 + (+3) - (2 - 6)', '3');
INSERT INTO exercises (type, statement, solution) VALUES (210, '-8:(-5+1) \\cdot (-2)', '-4');
INSERT INTO exercises (type, statement, solution) VALUES (210, '(-4 -4 \\cdot 5) : (-3)', '8');
INSERT INTO exercises (type, statement, solution) VALUES (210, '10:(-9-1) - 1', '-2');
INSERT INTO exercises (type, statement, solution) VALUES (210, '8-9 \\cdot 2 - 5', '-15');
INSERT INTO exercises (type, statement, solution) VALUES (210, '10:(-2) + 2 \\cdot (-2)', '-9');
INSERT INTO exercises (type, statement, solution) VALUES (210, '(4 - 10) \\cdot (-5 -1)', '36');
INSERT INTO exercises (type, statement, solution) VALUES (210, '-5 -(+ 4) + (-2 + 7)', '-4');
INSERT INTO exercises (type, statement, solution) VALUES (210, '-2 - 4 \\cdot 2 + 9', '-1');
INSERT INTO exercises (type, statement, solution) VALUES (210, '4 \\cdot (-7 + 3) + 9', '-7');
INSERT INTO exercises (type, statement, solution) VALUES (210, '-(+9) -1 \\cdot (-8) - 5', '-6');
INSERT INTO exercises (type, statement, solution) VALUES (210, '8 - 7 \\cdot 2 + 11', '5');
INSERT INTO exercises (type, statement, solution) VALUES (210, '\\left[-(-3) - 4 \\cdot 2\\right] : (-5)', '1');
INSERT INTO exercises (type, statement, solution) VALUES (210, '-(+4)-6+(-1) \\cdot 4', '-14');
INSERT INTO exercises (type, statement, solution) VALUES (210, '2 - 2 \\cdot (-2) - 20', '-14');
INSERT INTO exercises (type, statement, solution) VALUES (210, '-3-\\left[8:(-4)\\right] - 10', '-11');
INSERT INTO exercises (type, statement, solution) VALUES (210, '6:(-3) - 2 \\cdot 2', '-6');
INSERT INTO exercises (type, statement, solution) VALUES (210, '-4:(2-4) -4', '-2');
INSERT INTO exercises (type, statement, solution) VALUES (210, '(-6+11) \\cdot (-1) + 1', '-4');
INSERT INTO exercises (type, statement, solution) VALUES (210, '12:(-3-1) +6', '3');
INSERT INTO exercises (type, statement, solution) VALUES (210, '(-1-6) \\cdot (2 - 5)', '21');
INSERT INTO exercises (type, statement, solution) VALUES (210, '\\left[4 + (-5)\\right] : (- 5+4)', '1');
INSERT INTO exercises (type, statement, solution) VALUES (210, '-1 + (+9) - (-8) \\cdot (-1)', '0');
INSERT INTO exercises (type, statement, solution) VALUES (210, '-5 \\cdot (-1 -4) - 12', '13');
INSERT INTO exercises (type, statement, solution) VALUES (210, '(-5 + 8) \\cdot (-4+1)', '-9');
INSERT INTO exercises (type, statement, solution) VALUES (210, '- 6:(-1-2) - 8', '-6');
INSERT INTO exercises (type, statement, solution) VALUES (210, '-2:2 -  2 \\cdot 1', '-3');
INSERT INTO exercises (type, statement, solution) VALUES (210, '4 - 6 \\cdot (-1) - 12', '-2');
INSERT INTO exercises (type, statement, solution) VALUES (210, '-4 + (5-8) - 7', '-14');
INSERT INTO exercises (type, statement, solution) VALUES (210, '- 4 + 2 \\cdot 4 - 8', '-4');
INSERT INTO exercises (type, statement, solution) VALUES (210, '(-5 + 2) \\cdot (1 - 7)', '18');
INSERT INTO exercises (type, statement, solution) VALUES (210, '(-1 + 4 \\cdot 2) \\cdot (-2)', '-14');
INSERT INTO exercises (type, statement, solution) VALUES (210, '(-1 + 11) : (-4 + 2)', '-5');
INSERT INTO exercises (type, statement, solution) VALUES (210, '(-5 - 5) \\cdot 4 + 8', '-32');
INSERT INTO exercises (type, statement, solution) VALUES (210, '(-2 \\cdot 3 + 10) : (-1)', '-4');
INSERT INTO exercises (type, statement, solution) VALUES (210, '(-2+5) \\cdot (-1-4)', '-15');
INSERT INTO exercises (type, statement, solution) VALUES (210, '5-9-1 \\cdot (-1)', '-3');
INSERT INTO exercises (type, statement, solution) VALUES (210, '10 : (-3+1) - (-4)', '-1');
INSERT INTO exercises (type, statement, solution) VALUES (210, '\\left[5+(-1)\\right] \\cdot (-4 - 3)', '-28');
INSERT INTO exercises (type, statement, solution) VALUES (210, '4-8 \\cdot (-1) - 16', '-4');
INSERT INTO exercises (type, statement, solution) VALUES (210, '6 \\cdot (1 -3 - 2)', '-24');
INSERT INTO exercises (type, statement, solution) VALUES (210, '-1-4:(-2) \\cdot (-1)', '-3');
INSERT INTO exercises (type, statement, solution) VALUES (210, '12 :(-5-1) - 5', '-7');
INSERT INTO exercises (type, statement, solution) VALUES (210, '\\left[(-10+6) - (-2)\\right] \\cdot 8', '-16');
INSERT INTO exercises (type, statement, solution) VALUES (210, '14 : (-6-8) + 9', '8');
INSERT INTO exercises (type, statement, solution) VALUES (210, '\\left[-3 - (-1)\\right]:(-2+4)', '-1');
INSERT INTO exercises (type, statement, solution) VALUES (210, '(6 -12) \\cdot (-1+6)', '-30');
INSERT INTO exercises (type, statement, solution) VALUES (210, '\\left[6 - (+7) - (-2)\\right] \\cdot (-4)', '-4');
INSERT INTO exercises (type, statement, solution) VALUES (210, '24:(-4+2-10)', '-2');
INSERT INTO exercises (type, statement, solution) VALUES (210, '12:(-3-3) - 2', '-4');
INSERT INTO exercises (type, statement, solution) VALUES (210, '4 - 6 \\cdot 4 + 9', '-11');
INSERT INTO exercises (type, statement, solution) VALUES (210, '-6-6+(-2)+(+10)', '-4');
INSERT INTO exercises (type, statement, solution) VALUES (210, '5 \\cdot (-4+3) + 20', '15');
INSERT INTO exercises (type, statement, solution) VALUES (210, '4+2 \\cdot (-1-2)', '-2');
INSERT INTO exercises (type, statement, solution) VALUES (210, '\\left[-(-2) - 5 \\cdot 2\\right]:(-2)', '4');
INSERT INTO exercises (type, statement, solution) VALUES (210, '\\left[-8 - (-2)\\right]:(8-11)', '2');
INSERT INTO exercises (type, statement, solution) VALUES (210, '(5 -19): (-10+3)', '2');
INSERT INTO exercises (type, statement, solution) VALUES (210, '-(-4) \\cdot (-1-6) + 9', '-19');
INSERT INTO exercises (type, statement, solution) VALUES (210, '-1 + (4 -4 \\cdot 2)', '-5');
INSERT INTO exercises (type, statement, solution) VALUES (210, '1 - (-3 -4) \\cdot (-2)', '-13');
INSERT INTO exercises (type, statement, solution) VALUES (210, '(-5 + 2) \\cdot (-9+5)', '12');
INSERT INTO exercises (type, statement, solution) VALUES (210, '(5 - 7 + 1) : (-1)', '1');
INSERT INTO exercises (type, statement, solution) VALUES (210, '-15 : (-5) - 4 + 9', '8');
INSERT INTO exercises (type, statement, solution) VALUES (210, '12 : (-4-2) + 7', '5');
INSERT INTO exercises (type, statement, solution) VALUES (210, '-12 + \\left[4 \\cdot (-2)\\right] +16', '-4');
INSERT INTO exercises (type, statement, solution) VALUES (210, '\\left[-4 - (+1) +1\\right] : (2-4)', '2');
