INSERT INTO exercises (type, statement, solution) VALUES (211, '5 - 9 \\cdot (-1) -  3:(-3) - 2 \\cdot 2', '16');
INSERT INTO exercises (type, statement, solution) VALUES (211, '-1 + 4 \\cdot (-2) - 5 : (-5) + 1 \\cdot (-1)', '-9');
INSERT INTO exercises (type, statement, solution) VALUES (211, '\\left[ 5- (-3):(-3) \\right] \\cdot -2 - 2', '-10');
INSERT INTO exercises (type, statement, solution) VALUES (211, '\\left[ -4:(2-6) -4 \\right] \\cdot (-1 - 2)', '9');
INSERT INTO exercises (type, statement, solution) VALUES (211, '2 - \\left[ (-6+8) \\cdot (-1) + 5 \\right] \\cdot (-1)', '5');
INSERT INTO exercises (type, statement, solution) VALUES (211, '\\left[ 10:(-4-1) +6 \\right] \\cdot (3 - 6)', '-12');
INSERT INTO exercises (type, statement, solution) VALUES (211, '\\left[ (-1-3) \\cdot (2 - 3) \\right] : (1 - 2 - 1)', '-2');
INSERT INTO exercises (type, statement, solution) VALUES (211, '\\left[ 4 + (-7) \\right] : (- 5+4) - ( 2- 6)', '7');
INSERT INTO exercises (type, statement, solution) VALUES (211, '\\left[ -1 + (+4) - (-8) \\right] \\cdot (-2) + 10', '-12');
INSERT INTO exercises (type, statement, solution) VALUES (211, '\\left[ -5 \\cdot (-1 - 1) - 12 \\right] \\cdot (4 - 7)', '6');
INSERT INTO exercises (type, statement, solution) VALUES (211, '\\left[ (-5 + 7) \\cdot (-4+1) \\right] \\cdot \\left[ (-5 + 7) \\cdot (-4+1) \\right]', '36');
INSERT INTO exercises (type, statement, solution) VALUES (211, '\\left[ - 6:(-1-1) - 8 \\right] : (-1 + 6)', '-1');
INSERT INTO exercises (type, statement, solution) VALUES (211, '-4:2 -  2 \\cdot 1 - 4 \\cdot 2', '-12');
INSERT INTO exercises (type, statement, solution) VALUES (211, '\\left[ 4 - 6 \\cdot (-1) - 7 \\right] : (-1-2)', '-1');
INSERT INTO exercises (type, statement, solution) VALUES (211, '\\left[ -4 + (5-6) - 7 \\right] : \\left[  5 \\cdot (-2) +4 \\right]', '2');
INSERT INTO exercises (type, statement, solution) VALUES (211, '\\left[ 1 - 2 \\cdot (-2) - 8 \\right] - \\left[ 2+2 \\cdot (-3) \\right]', '1');
INSERT INTO exercises (type, statement, solution) VALUES (211, '\\left[ (-4 + 2) \\cdot (5 - 7) \\right] \\cdot (-1 - 7)', '-32');
INSERT INTO exercises (type, statement, solution) VALUES (211, '\\left[ (-4 + 4 \\cdot 2) \\cdot (-2) \\right] : (8-12)', '2');
INSERT INTO exercises (type, statement, solution) VALUES (211, '\\left[ (-5 - 5) \\cdot 2 + 8 \\right] : \\left[ (-1 + 5) : (-4 + 2) \\right]', '6');
INSERT INTO exercises (type, statement, solution) VALUES (211, '\\left[ (-4 \\cdot 3 + 10) : (-1) \\right]  \\cdot  \\left[ (-4+5) \\cdot (-1-4) \\right]', '-10');
INSERT INTO exercises (type, statement, solution) VALUES (211, '5-7-1 \\cdot (-1) - \\left[ 10 : (-6+1) - (-4) \\right]', '-3');
INSERT INTO exercises (type, statement, solution) VALUES (211, '\\left[ 5+(-4) \\right] \\cdot (-4 - 3) -8 \\cdot (-1) - 16', '-15');
INSERT INTO exercises (type, statement, solution) VALUES (211, '\\left[ 6 \\cdot (5 -8 - 2) \\right] - \\left[ -8:(4 - 6) - 10 \\right]', '-24');
INSERT INTO exercises (type, statement, solution) VALUES (211, '\\left[ -(-1)+(-2)+(-3)-(-4) \\right]\\cdot \\left[ 4 + 2 \\cdot (-4) - 1 \\right]', '0');
INSERT INTO exercises (type, statement, solution) VALUES (211, '\\left[ -4 -5 -1 + 8 \\right]  \\cdot \\left[ -4 \\cdot (1 - 5) - 10 \\right]', '-12');
INSERT INTO exercises (type, statement, solution) VALUES (211, '\\left[ 5+(-7) - 2 \\cdot (-2) \\right] - \\left[ -(-2 \\cdot 4) - 9 + 5 \\right]', '-2');
INSERT INTO exercises (type, statement, solution) VALUES (211, '- \\left[ 12:(-4-2) + 9 \\right] + \\left[ -5 - (-1 -2) \\right] \\cdot 5', '-17');
INSERT INTO exercises (type, statement, solution) VALUES (211, '\\left[ -7+8:(-4) + 5 \\right] \\cdot \\left[ -6:(1-4) -8 \\right]', '24');
INSERT INTO exercises (type, statement, solution) VALUES (211, '\\left[ 4-(+5)+(-1) \\cdot 2 \\right] + \\left[ (-1+9):(-3-1) \\right]', '-5');
INSERT INTO exercises (type, statement, solution) VALUES (211, '7 \\cdot (-4+6) - 15 - 4:(-2-2)', '0');
INSERT INTO exercises (type, statement, solution) VALUES (211, '-1+5 \\cdot (-2) - 2 - \\left[ -7+(+8) -(-4) +(-7) \\right]', '-11');
INSERT INTO exercises (type, statement, solution) VALUES (211, '\\left[ 6:(-4+1)-10 \\right] : \\left[ (-4 -1 \\cdot 5) : (-3) \\right]', '-4');
INSERT INTO exercises (type, statement, solution) VALUES (211, '2 \\cdot (-1+4) - 7 - \\left[ -4 + (+2) - (2 - 5) \\right]', '-2');
INSERT INTO exercises (type, statement, solution) VALUES (211, '\\left[ -1 +(-4) \\right] \\cdot \\left[ -4 - (-4) \\right]', '0');
INSERT INTO exercises (type, statement, solution) VALUES (211, '\\left[ (9 - 10) \\cdot (-5 -1) \\right]:\\left[ 10:(-5) + 2 \\cdot (-2) \\right]', '-1');
INSERT INTO exercises (type, statement, solution) VALUES (211, '\\left[ 4 \\cdot (-5 + 3) + 4 \\right] : \\left[ -(+7) -1 \\cdot (-10) - 5 \\right]', '2');
INSERT INTO exercises (type, statement, solution) VALUES (211, '\\left[ 8-9 \\cdot 2 + 5 \\right] \\cdot \\left[ -5 -(+ 5) + (-6 + 7)', ' \\right]');
INSERT INTO exercises (type, statement, solution) VALUES (211, '\\left[ -(-6) - 7 \\cdot 2 \\right] : (-4) - \\left[ 7 - 4 \\cdot 2 + 9 \\right]', '-6');
INSERT INTO exercises (type, statement, solution) VALUES (211, '\\left[ 3 - 5 \\cdot 4 + 14 \\right] \\cdot \\left[ 4:(-5+1) \\cdot (-2) \\right]', '-6');
INSERT INTO exercises (type, statement, solution) VALUES (211, '4-6+(-1) \\cdot 4 - \\left[ 6 - 8 \\cdot (-2) -10 \\right]', '-18');
INSERT INTO exercises (type, statement, solution) VALUES (211, '-5-\\left[ 4:(-2) \\right] - 10 - \\left[ 10:(-9+7) - 1 \\right]', '-7');
INSERT INTO exercises (type, statement, solution) VALUES (211, '\\left[ -(+6) - (-2) \\right] : (5 - 7) - \\left[ 5:(-5)-2 \\right]', '5');
INSERT INTO exercises (type, statement, solution) VALUES (211, '\\left[ 2-6 \\cdot 2 +3 \\right] \\cdot \\left[ 6:(-1+4) - 6 \\right]', '28');
INSERT INTO exercises (type, statement, solution) VALUES (211, '\\left[ 6+(-8) - (-1) \\right] \\cdot 5 - \\left[ 5 - (6 - 9) - 9 \\right]', '4');
INSERT INTO exercises (type, statement, solution) VALUES (211, '- \\left[ (-4-4):(-2) \\cdot (-1) \\right] \\cdot \\left[ 10 :(-4-1) - 5 \\right]', '-28');
INSERT INTO exercises (type, statement, solution) VALUES (211, '- \\left[ -4-4:(-2) \\cdot (-1) \\right] - \\left[ (6-9) \\cdot (7-10) \\right]', '-11');
INSERT INTO exercises (type, statement, solution) VALUES (211, '\\left[ (-8+6) - (-2) \\right] \\cdot 4 - \\left[ 8 : (-6-2) + 9 \\right]', '-8');
INSERT INTO exercises (type, statement, solution) VALUES (211, '\\left[ -5 - (-1) \\right]:(-2-2)\\cdot \\left[ (6 -10) \\cdot (-1+6) \\right]', '-20');
INSERT INTO exercises (type, statement, solution) VALUES (211, '1+1 \\cdot (-1-2) + 5 \\cdot (-8+3) + 20', '-7');
INSERT INTO exercises (type, statement, solution) VALUES (211, '\\left[ 6 - (+9) - (-2) \\right] \\cdot (-1) +  8:(-4+2-6)', '0');
INSERT INTO exercises (type, statement, solution) VALUES (211, '\\left[ 10:(-3-2) - 2 \\right] \\cdot \\left[ 4 - 6 \\cdot 3 + 9 \\right]', '20');
INSERT INTO exercises (type, statement, solution) VALUES (211, '-8-6+(-2)+(+10) - \\left[ -(-4) - 5 \\cdot 2 \\right]:(-2)', '-9');
INSERT INTO exercises (type, statement, solution) VALUES (211, '\\left[ -8 - (-6) \\right]:(8-10) - \\left[ (5 - 9): (-10+14) \\right]', '2');
INSERT INTO exercises (type, statement, solution) VALUES (211, '- 1 - 1 -1 + 7 - \\left[ 8: (-7 +4 - 1) \\right]', '6');
INSERT INTO exercises (type, statement, solution) VALUES (211, '-(-8) \\cdot (-1-1) + 9 - \\left[ 2 - (-5 -4) \\cdot (-1) \\right]', '0');
INSERT INTO exercises (type, statement, solution) VALUES (211, '-5 + (4 -7 \\cdot 2) + (-5 + 4) \\cdot (-8+2)', '-9');
INSERT INTO exercises (type, statement, solution) VALUES (211, '\\left[ -10 : (-5) - 4 + 9 \\right]:\\left[ (5 - 8 + 1) : 2  \\right]', '-7');
INSERT INTO exercises (type, statement, solution) VALUES (211, '-2 + \\left[ 4 \\cdot (-2) \\right] +16 - \\left[ (5-6):(-1+2) \\right]', '7');
INSERT INTO exercises (type, statement, solution) VALUES (211, '\\left[ -5 - (+6) +1 \\right] : (4+1) - \\left[ 6 : (-4-2) + 5 \\right]', '-6');
INSERT INTO exercises (type, statement, solution) VALUES (211, '\\left[ (4-8) \\cdot  (-5 -1) \\right]:\\left[ 5:(-4-1) -1 \\right]', '-12');
INSERT INTO exercises (type, statement, solution) VALUES (211, '\\left[ 6:(-3) + 4 \\right] \\cdot (-1) \\cdot (-1-1+4-5)', '6');
INSERT INTO exercises (type, statement, solution) VALUES (211, '\\left[ 6-(-2) \\right]:(-2-2) - \\left[ 6-(-2):(-2) \\right] \\cdot (-2)', '8');
INSERT INTO exercises (type, statement, solution) VALUES (211, '\\left[ 8 - 10 \\cdot 2 + 5 \\right] \\cdot \\left[ 6:(-5-1) +6 \\right]', '-35');
INSERT INTO exercises (type, statement, solution) VALUES (211, '\\left[ - 5 - (+2 - 8) : (-2) \\right] \\cdot \\left[ 4 \\cdot (-2-1) - 1 \\right]', '26');
INSERT INTO exercises (type, statement, solution) VALUES (211, '\\left[ \\left[ 10 - (+11) \\right] \\cdot (-2 + 7) \\right] - \\left[ -4 : (5 - 9) - 4 \\right]', '-2');
INSERT INTO exercises (type, statement, solution) VALUES (211, '6 - ( -10 + 18) - 1 + \\left[ -5 - (+4- 6) - 1 \\right]', '-7');
INSERT INTO exercises (type, statement, solution) VALUES (211, '- \\left[ (-7 +1) \\cdot (-3 - 3) \\right]:\\left[ -9 : 9 - 1 + 6 \\right]', '-9');
INSERT INTO exercises (type, statement, solution) VALUES (211, '8:(-7-1) +1 - \\left[ 5 - (-6) - 12 \\right] \\cdot 8', '8');
INSERT INTO exercises (type, statement, solution) VALUES (211, '\\left[ -1 + (-8) +4 \\right] \\cdot 3 : \\left[ 2 - ( -4 +8) - 1 \\right]', '5');
INSERT INTO exercises (type, statement, solution) VALUES (211, '\\left[ 8:(-4) - (-1) - 1 \\right] \\cdot \\left[ 4 \\cdot (-2) \\cdot 2 : (-8) \\right]', '-4');
INSERT INTO exercises (type, statement, solution) VALUES (211, '\\left[ 5 - (+2 - 9) \\right] : (-2) - \\left[  4 - 14 -8 \\cdot (-2) \\right]', '-12');
INSERT INTO exercises (type, statement, solution) VALUES (211, '-6:(-6) + \\left[ 5 \\cdot (-2) \\right] - \\left[ 10:(-2-3) - 5 \\right]', '-2');
INSERT INTO exercises (type, statement, solution) VALUES (211, '\\left[ (-5-5) : (4 -5) \\right] \\cdot \\left[ - 7 - 2 \\cdot 2 + 4 \\right]', '-70');
INSERT INTO exercises (type, statement, solution) VALUES (211, '-(+2) -1 \\cdot 4 + 5 - \\left[ - 4 \\cdot (-5 + 6) + 7 \\right]', '- 4');
INSERT INTO exercises (type, statement, solution) VALUES (211, '\\left[ 2 - 4 \\cdot 6 + 14 \\right]:\\left[ -8:(-5+1) \\cdot (-2) \\right]', '2');
INSERT INTO exercises (type, statement, solution) VALUES (211, '-4 + (+3) - (2 - 6) - \\left[ 5:(-4-1)-10 \\right]', '14');
INSERT INTO exercises (type, statement, solution) VALUES (211, '\\left[ (-4 -4 \\cdot 5) : (-3) \\right]:\\left[ 10:(-9-1) - 1 \\right]', '-4');
INSERT INTO exercises (type, statement, solution) VALUES (211, '8-9 \\cdot 2 - 5 + (4 - 10) \\cdot (-5 -1)', '21');
INSERT INTO exercises (type, statement, solution) VALUES (211, '\\left[ -(-2) - 6 \\cdot 2 \\right] : (-5) \\cdot \\left[ 4 \\cdot (-7 + 3) + 9 \\right]', '-14');
INSERT INTO exercises (type, statement, solution) VALUES (211, '\\left[ -5 -(+ 4) + (-2 + 7) \\right] : \\left[ -2 - 4 \\cdot 2 + 9 \\right]', '4');
INSERT INTO exercises (type, statement, solution) VALUES (211, '10:(-2) + 2 \\cdot (-2) -(+9) -1 \\cdot (-8) - 5', '-15');
INSERT INTO exercises (type, statement, solution) VALUES (211, '-\\left[ 8 - 7 \\cdot 2 + 11 \\right] - \\left[ -(-3) - 4 \\cdot 2 \\right] : (-5)', '-9');
INSERT INTO exercises (type, statement, solution) VALUES (211, '-(+4)-6+(-1) \\cdot 4 + 2 - 2 \\cdot (-2) - 20', '-28');
INSERT INTO exercises (type, statement, solution) VALUES (211, '\\left[ (-6+11) \\cdot (-1) + 1 \\right] : \\left[ -4:(2-4) -4 \\right]', '2');
INSERT INTO exercises (type, statement, solution) VALUES (211, '-3-\\left[ 8:(-4) \\right] - 10 - \\left[ 12:(-3-1) +6 \\right]', '-14');
INSERT INTO exercises (type, statement, solution) VALUES (211, '-\\left[ 6:(-3) - 2 \\cdot 2 \\right] : \\left[ 4 + (-5) \\right] : (- 5+4)', '-2');
INSERT INTO exercises (type, statement, solution) VALUES (211, '(-5 + 8) \\cdot (-4+1) - \\left[ -5 \\cdot (-1 -4) - 12 \\right]', '-22');
INSERT INTO exercises (type, statement, solution) VALUES (211, '\\left[ - 6:(-1-2) - 8 \\right] \\cdot \\left[ -2:2 -  2 \\cdot 1 \\right]', '18');
INSERT INTO exercises (type, statement, solution) VALUES (211, '\\left[ -4 + (5-8) - 7 \\right]:\\left[ 4 - 6 \\cdot (-1) - 12 \\right]', '7');
INSERT INTO exercises (type, statement, solution) VALUES (211, '-1 + (+9) - (-8) \\cdot (-1) - \\left[ (-1-6) \\cdot (2 - 5) \\right]', '-21');
INSERT INTO exercises (type, statement, solution) VALUES (211, '(-1 + 4 \\cdot 2) \\cdot (-2) + (-5 + 2) \\cdot (1 - 7)', '4');
INSERT INTO exercises (type, statement, solution) VALUES (211, '\\left[ (6 -12) \\cdot (-1+6) \\right]:\\left[ (-2+5) \\cdot (-1-4) \\right]', '2');
INSERT INTO exercises (type, statement, solution) VALUES (211, '\\left[ 5-9-1 \\cdot (-1) \\right] \\cdot \\left[  - 4 + 2 \\cdot 4 - 8 \\right]', '12');
INSERT INTO exercises (type, statement, solution) VALUES (211, '-\\left[ 5+(-1) \\right] \\cdot (-4 - 3) + (-5 - 5) \\cdot 4 + 8', '-4');
INSERT INTO exercises (type, statement, solution) VALUES (211, '\\left[ (-2 \\cdot 3 + 10) : (-1) \\right] : \\left[ 4-8 \\cdot (-1) - 16  \\right]', '1');
INSERT INTO exercises (type, statement, solution) VALUES (211, '(-1 + 11) : (-4 + 2) - \\left[ 6 \\cdot (1 -3 - 2) \\right]', '-19');
INSERT INTO exercises (type, statement, solution) VALUES (211, '\\left[ (-5 + 2) \\cdot (-9+5) \\right] : \\left[ 12:(-3-3) - 2 \\right]', '-3');
INSERT INTO exercises (type, statement, solution) VALUES (211, '\\left[ (-10+6) - (-2) \\right] \\cdot 8 - \\left[ 6 - (+7) - (-2) \\right] \\cdot (-4)', '-12');
INSERT INTO exercises (type, statement, solution) VALUES (211, '-(-4) \\cdot (-1-6) + 9 + 5 \\cdot (-4+3) + 20', '-4');
INSERT INTO exercises (type, statement, solution) VALUES (211, '\\left[ 10 : (-3+1) - (-4) \\right] \\cdot \\left[ -1-4:(-2) \\cdot (-1) \\right]', '3');
INSERT INTO exercises (type, statement, solution) VALUES (211, '\\left[ -3 - (-1) \\right]:(-2+4) + 12 :(-5-1) - 5', '-8');
INSERT INTO exercises (type, statement, solution) VALUES (211, '\\left[ 14 : (-6-8) + 9 \\right] : \\left[ 24:(-4+2-10) \\right]', '-4');
INSERT INTO exercises (type, statement, solution) VALUES (211, '-6-6+(-2)+(+10) - \\left[ -(-2) - 5 \\cdot 2 \\right]:(-2)', '-8');
INSERT INTO exercises (type, statement, solution) VALUES (211, '\\left[ (5 -19): (-10+3) \\right]  \\cdot \\left[ -1 + (4 -4 \\cdot 2) \\right]', '-10');
INSERT INTO exercises (type, statement, solution) VALUES (211, '4 - 6 \\cdot 4 + 9 + 1 - (-3 -4) \\cdot (-2)', '-24');
INSERT INTO exercises (type, statement, solution) VALUES (211, '\\left[ 4+2 \\cdot (-1-2) \\right]:\\left[ (5 - 7 + 1) : (-1) \\right]', '-2');
INSERT INTO exercises (type, statement, solution) VALUES (211, '- \\left[ -15 : (-5) - 4 + 9 \\right] \\cdot \\left[ 12 : (-4-2) + 7 \\right]', '-40');
INSERT INTO exercises (type, statement, solution) VALUES (211, '\\left[ -8 - (-2) \\right]:(8-11) + \\left[ -4 - (+1) +1 \\right] : (2-4)', '4');
INSERT INTO exercises (type, statement, solution) VALUES (211, '-12 + \\left[ 4 \\cdot (-2) \\right] +12 - \\left[ 3 : (-3) - 1 \\right]', '2');
INSERT INTO exercises (type, statement, solution) VALUES (211, '\\left[ (-5 - 3) : (-4 +10 + 2) - 5 \\right] \\cdot (-1 + 4)', '18');
INSERT INTO exercises (type, statement, solution) VALUES (211, '(- 9 - 5) : (-1 + 8) - 5 \\cdot 2 + (-4) \\cdot (-4)', '4');
INSERT INTO exercises (type, statement, solution) VALUES (211, '-15 : \\left[ -5 \\cdot (-2) + 5 \\right] - 4 - 2 \\cdot (-3)', '-1');
INSERT INTO exercises (type, statement, solution) VALUES (211, '\\left[ -1 + (+4) - (-8) \\right] \\cdot (-2) + 5 \\cdot (--3+6)', '-7');
